# Generated by Django 4.0.4 on 2022-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_ticket_options_ticket_time_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_edited',
            field=models.DateTimeField(blank=True),
        ),
    ]
