# Generated by Django 4.0.4 on 2022-05-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_review_time_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created']},
        ),
    ]
