"""
Django settings for litreview project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/

admin           EL-walid_1234@+
Si-Mo           Courtoi26
Souzane         Bitros95+
Nadej           Kilom95+7
Florent         Kabis95200+
François        Limoge92008
EL-walid        Base1304@+

Powered By EL-WALID EL-KHABOU
"""

from pathlib import Path
# Importation de la classe Path du module pathlib, qui permet de manipuler les chemins de fichiers d'une manière plus
# élégante et orientée objet.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Définition du répertoire de base du projet. Utilisé pour construire des chemins relatifs dans le reste du fichier.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^9t4@)qh)bdw27y*yf---mmgx)@*e(ef(m&6u8e#oe4*bu4&5&'
# Clé secrète utilisée pour la signature de cookies et d'autres fonctions de sécurité. Doit être gardée secrète en
# production.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Activation du mode de débogage. Doit être désactivé en production pour des raisons de sécurité.

ALLOWED_HOSTS = []
# Liste des noms d'hôte qui sont autorisés à servir cette application. En mode débogage, la liste peut être vide.


# Liste des applications installées dans ce projet. Inclut les applications intégrées à Django et mes propres
# applications.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'ticketing',
    'subscription',
]

# Liste des classes middleware utilisées par le système de requêtes/réponses de Django.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Chemin vers le module qui contient les URL de niveau racine du projet.
ROOT_URLCONF = 'litreview.urls'

# Configuration du moteur de templates de Django. Définit comment les templates sont chargés et rendus.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Chemin vers l'application WSGI utilisée pour servir ce projet.
WSGI_APPLICATION = 'litreview.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# Configuration de la base de données. Ici, SQLite est utilisé comme système de gestion de base de données.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
# Liste des validateurs de mots de passe utilisés par le système d'authentification.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 5, }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
# Code de la langue par défaut.
LANGUAGE_CODE = 'fr-fr'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Paris'

# Activation du système de traduction internationalisé.
USE_I18N = True

# Activation de la gestion des fuseaux horaires.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# URL utilisée pour servir les fichiers statiques.
STATIC_URL = 'static/'

# Répertoires contenant les fichiers statiques.
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

# Type de champ utilisé pour les clés primaires automatiques.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Chemin vers le modèle d'utilisateur personnalisé
AUTH_USER_MODEL = 'authentication.User'

# URL vers la page de connexion.
LOGIN_URL = 'login'

# URL de redirection après une connexion réussie.
LOGIN_REDIRECT_URL = 'home'

# URL utilisée pour servir les fichiers médias.
MEDIA_URL = '/media/'

# Répertoire où les fichiers médias sont stockés sur le disque.
MEDIA_ROOT = BASE_DIR.joinpath('media/')
