# Generated by Django 4.0.4 on 2022-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/home/pousti/coursoc/ocrp9/media/empty_avatar.png', upload_to='', verbose_name='Photo de profil'),
        ),
    ]
