# Generated by Django 4.2 on 2023-08-04 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reviewed',
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.ticket'),
        ),
    ]
