# Generated by Django 4.2 on 2023-08-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_ticket_reviewed_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'critique', 'verbose_name_plural': 'critiques'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Demande de critique'},
        ),
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'Suivi des utilisateurs'},
        ),
    ]
