# Generated by Django 4.2 on 2023-08-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
